[all:vars]
ansible_user=ansible
ansible_ssh_private_key_file=/home/aqinfra/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3

[orc]
VM-AQ-BRAIN ansible_host=10.100.100.201

[dat]
VM-AQ-DATA ansible_host=10.100.100.202

[cmp]
VM-AQ-COMPUTE ansible_host=10.100.100.203

[ai]
VM-AQ-IA ansible_host=10.100.100.204

[trd]
VM-AQ-TRADE ansible_host=10.100.100.205
