[all:vars]
ansible_user=ansible
ansible_ssh_private_key_file=/home/ansible/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3

[orc]
tr-infra-brain-01 ansible_host=10.100.100.200

[dat]
tr-infra-data-01 ansible_host=10.100.100.201

[cmp]
tr-infra-compute-01 ansible_host=10.100.100.202

[lab]
tr-infra-lab-01 ansible_host=10.100.100.203
